Bump version to 1.0.7
g7/jolla-settings-screenmonitor pull request #6
Opened 2024-04-04 21:23 UTC by dev-nis

- Fix Icon size (thanks to https://github.com/carmenfdezb )
- Add Spanish translation (thanks to https://github.com/carmenfdezb )
- Add German translation
- Fix the build for aarch64 on modern SailfishOS-versions:
- Changed call to systemd to new path
- Fixed inclusion of systemd-service in RPM packaging

2024-05-04 11:20 UTC, g7 requested changes
Thanks for resurrecting this! :100: 

Some minor comments for some unneeded artifacts that can be gitignored, otherwise looks good to me

2024-05-04 11:20 UTC, g7 commented on jolla-settings-screenmonitor.pro.user.0a580b9
Is this needed? Looks some qtcreator user specific settings (I think they can be gitignored)

2024-05-04 11:20 UTC, g7 commented on service/ScreenMonitor
Build artifact - can be removed and gitignored

2024-05-04 19:58 UTC, dev-nis commented on jolla-settings-screenmonitor.pro.user.0a580b9
I don't think it's needed. I removed it and added it to .gitignore

2024-05-04 19:58 UTC, dev-nis commented on service/ScreenMonitor
Done!

2024-05-22 22:26 UTC, g7 commented
Thank you very much! Sorry for merging this late

2024-05-22 22:26 UTC, g7 approved these changes

2024-05-22 22:27 UTC, merged

2024-05-23 07:48 UTC, dev-nis commented
> Thank you very much! Sorry for merging this late

No problem!
Should I remove my forked version from OpenRepos then?